### ISSUE TITLE
How to setup the environment

### ISSUE THREAD

**Issue by fyy623** [SEDenmarkLab/Lucid_Somnambulist#34]
Hi, I am stuck at the last phase of the setup.

I git cloned Molli to the directory, ran ```pip install .```, but received an error at ```python -c "import somn"```, where it says 

`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yyf/Lucid_Somnambulist/Lucid_Somnambulist/somn/__init__.py", line 1, in <module>
    from . import build
  File "/home/yyf/Lucid_Somnambulist/Lucid_Somnambulist/somn/build/__init__.py", line 10, in <module>
    from .parsing import InputParser, cleanup_handles
  File "/home/yyf/Lucid_Somnambulist/Lucid_Somnambulist/somn/build/parsing.py", line 1, in <module>
    import molli as ml
ModuleNotFoundError: No module named 'molli'
`

I believe it has something to do with the location the Molli package, which brings my question: 

In Readme, it says "Finally, download and install this package by running the following command in the top-level directory (/path/to/package/Lucid_Somnambulist/):", I assume this actually means Lucid_Somnambulist/Lucid_Somnambulist , rather than the so called top Lucid_Somnambulist/, as the there is no env config file for the setup. So I installed Molli under Lucid_Somnambulist/Lucid_Somnambulist, followed the procedure mentioned above and got stuck there.

Any suggestion?

@ianrinehart @nhadler

**Comment by fyy623** [comment]
Fixed, a few notes:

1. molli should not be installed at top top directory, but rather Lucid_Somnambulist/Lucid_Somnambulist
2. to install molli smoothly, run ```pip install git+https://github.com/SEDenmarkLab/molli_firstgen.git#egg=molli``` with reference to [the top answer in the post](https://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github)

it's probably worth it to update the readme for clarification.

i will close this issue myself, but yet I'm still lost at where to actually start testing around....
